---
title: "kateto tutorial"
output: html_document
date: "2022-10-01"
---

Following tutorial at:

[https://kateto.net/network-visualization](https://kateto.net/network-visualization)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
par(bg="gray40")
col.tr <- grDevices::adjustcolor("557799", alpha=0.7)
plot(x=1:5, y=rep(5,5), pch=19, cex=12, col=col.tr, xlim=c(0,6)) 
```

Load data

```{r}
nodes <- read.csv("data/Dataset1-Media-Example-NODES.csv", header=T, as.is=T)
links <- read.csv("data/Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)
```

Create an igraph object. 

```{r}
library(igraph)
library(magrittr)
```

```{r}
net <- graph_from_data_frame(d = links, vertices = nodes, directed = TRUE)
net
```

```{r}
E(net)$type
```

```{r}
plot(net)
```

```{r}
net %>%
  simplify(remove.multiple = FALSE, remove.loops = TRUE) %>%
  plot()
```

```{r}
net %>%
  simplify(remove.multiple = FALSE, remove.loops = TRUE) %>%
  plot(edge.arrow.size = .4, vertex.label = NA)
```

```{r}
nodes2 <- read.csv("data/Dataset2-Media-User-Example-NODES.csv", header=T, as.is=T)
links2 <- read.csv("data/Dataset2-Media-User-Example-EDGES.csv", header=T, row.names=1)
```

```{r}
links2 <- as.matrix(links2)
dim(links2)
dim(nodes2)
```

```{r}
net2 <- graph_from_incidence_matrix(links2)
table(V(net2)$type)
```

```{r}
# Plot with curved edges (edge.curved=.1) and reduce arrow size:
# Note that using curved edges will allow you to see multiple links
# between two nodes (e.g. links going in either direction, or multiplex links)
plot(net, edge.arrow.size=.4, edge.curved=.1)
```

```{r}
# Set edge color to light gray, the node & border color to orange 
# Replace the vertex label with the node names stored in "media"
plot(net, edge.arrow.size=.2, edge.color="orange",
     vertex.color="orange", vertex.frame.color="#ffffff",
     vertex.label=V(net)$media, vertex.label.color="black") 
```

```{r}
# Generate colors based on media type:
colrs <- c("gray50", "tomato", "gold")
V(net)$color <- colrs[V(net)$media.type]

# Compute node degrees (#links) and use that to set node size:
deg <- degree(net, mode="all")
V(net)$size <- deg*3
# We could also use the audience size value:
V(net)$size <- V(net)$audience.size*0.6

# The labels are currently node IDs.
# Setting them to NA will render no labels:
V(net)$label <- NA

# Set edge width based on weight:
E(net)$width <- E(net)$weight/6

#change arrow size and edge color:
E(net)$arrow.size <- .2
E(net)$edge.color <- "gray80"

# We can even set the network layout:
graph_attr(net, "layout") <- layout_with_lgl
plot(net) 
```

```{r}
E(net)$width
```

```{r}
plot(net, edge.color="orange", vertex.color="gray50") 
```

```{r}
set.seed(123)
plot(net) 
legend(x=-1.5, y=-1.1, c("Newspaper","Television", "Online News"), pch=21,
       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)
```

```{r}
plot(net, vertex.shape="none", vertex.label=V(net)$media, 
     vertex.label.font=2, vertex.label.color="gray40",
     vertex.label.cex=.7, edge.color="gray85")
```

```{r}
net.bg <- sample_pa(100) 
V(net.bg)$size <- 8
V(net.bg)$frame.color <- "white"
V(net.bg)$color <- "orange"
V(net.bg)$label <- "" 
E(net.bg)$arrow.mode <- 0
plot(net.bg)
```

```{r}
plot(net.bg, layout=layout_randomly)
```

```{r}
l <- layout_in_circle(net.bg)
plot(net.bg, layout=l)
```

```{r}
l <- layout_on_sphere(net.bg)
plot(net.bg, layout=l)
```

```{r}
l <- layout_with_fr(net.bg)
plot(net.bg, layout=l)
```

```{r}
l <- layout_with_fr(net.bg, niter=50)
plot(net.bg, layout=l)
```

```{r}
ws  <-  c(1, rep(100, ecount(net.bg)-1))
lw <- layout_with_fr(net.bg, weights=ws)
plot(net.bg, layout=lw) 
```

```{r}
library(ggplot2)
library(ggraph)
```

```{r}
net %>%
  ggraph(layout = "lgl") +
  geom_node_point() +
  geom_edge_arc() +
  labs(title = "No nodes")
```

```{r}
ggraph(net, layout="lgl") +
  geom_edge_fan(color="gray50", width=0.8, alpha=0.5) + 
  geom_node_point(color=V(net)$color, size=8) +
  theme_void()
```

```{r}
ggraph(net, layout = 'linear') + 
    geom_edge_arc(color = "orange", width=0.7) +
    geom_node_point(size=5, color="gray50") +
    theme_void()
```

```{r}
ggraph(net, layout="lgl") +
  geom_edge_link(aes(color = type)) +           # colors by edge type 
  geom_node_point(aes(size = audience.size)) +  # size by audience size  
  theme_void()
```

```{r}
ggraph(net,  layout = 'lgl') +
  geom_edge_arc(color="gray", strength=0.3) +            
  geom_node_point(color="orange", aes(size = audience.size)) +     
  geom_node_text(aes(label = media), size=3, color="gray50", repel=T) +
  theme_void()
```
